function [Vout] = polyWithHighPowerNonlinearity_coreFn(Vin,A,omegaPoleTs,AR,AI,alphaTs,betaTs,poly0,poly1,poly2,Vbias,LaserPower)
Pavg=(1+tanh(poly0.'*Vbias.^((0:length(poly0)-1).')))*0.5*LaserPower;
bInst1stOrder=zeros(length(Vin),length(A));
bInst2ndOrder=zeros(length(Vin),length(AR));
Vout=zeros(size(Vin));
Vout1=zeros(size(Vin));
bInst=zeros(size(Vin));
b=zeros(size(Vin));
omegaPoleInst=omegaPoleTs(:,1);
alphaTsInst=alphaTs(:,1);
betaTsInst=betaTs(:,1);
B1=exp(-omegaPoleInst.');
B2=exp(-alphaTsInst.');
C3=cos(betaTsInst.');
S3=sin(betaTsInst.');
QR=(AR.').*(1-B2.*C3) - (AI.').*B2.*S3;
QI=(AI.').*(1-B2.*C3) + (AR.').*B2.*S3;
i=1;
Vout(i)=(1+tanh(poly0.'*(Vin(i)+Vbias).^((0:length(poly0)-1).')))*0.5*LaserPower;
bInst(i)=Vout(i)-Pavg;
bInst1stOrder(i,:)=(A.').*(1-B1).*bInst(i);
bInst2ndOrder(i,:)=2*QR.*bInst(i);
b(i)=sum(bInst1stOrder(i,:))+sum(bInst2ndOrder(i,:));
i=2;
Vout(i)=(1+tanh((poly0+poly1*b(i-1)+poly2*b(i-1).^2).'*(Vin(i)+Vbias).^((0:length(poly0)-1).')))*0.5*LaserPower;
bInst(i)=Vout(i)-Pavg;
bInst1stOrder(i,:)=B1.*bInst1stOrder(i-1,:)+(A.').*(1-B1).*bInst(i);
bInst2ndOrder(i,:)=2*B2.*C3.*bInst2ndOrder(i-1,:) + 2*QR.*bInst(i) - 2*B2.*(QR.*C3 - QI.*S3).*bInst(i-1);
b(i)=sum(bInst1stOrder(i,:))+sum(bInst2ndOrder(i,:));
for i=3:length(Vin)
    Vout(i)=(1+tanh((poly0+poly1*b(i-1)+poly2*b(i-1).^2).'*(Vin(i)+Vbias).^((0:length(poly0)-1).')))*0.5*LaserPower;
    Vout1(i)=(1+tanh((poly0).'*(Vin(i)+Vbias).^((0:length(poly0)-1).')))*0.5*LaserPower;
    bInst(i)=Vout(i)-Pavg;
    bInst1stOrder(i,:)=B1.*bInst1stOrder(i-1,:)+(A.').*(1-B1).*bInst(i);
    bInst2ndOrder(i,:)=2*B2.*C3.*bInst2ndOrder(i-1,:) - B2.^2 .* bInst2ndOrder(i-2,:) + 2*QR.*bInst(i) - 2*B2.*(QR.*C3 - QI.*S3).*bInst(i-1);
    b(i)=sum(bInst1stOrder(i,:))+sum(bInst2ndOrder(i,:));
end
end
